version: "3.9"
services:
  pub:
    build: .
    image: cbodonnell/til-api
    ports:
      - 127.0.0.1:${PORT}:${PORT}
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - AUTH=${AUTH}
      - CLIENT=${CLIENT}
      - RSA_PUBLIC_KEY=/etc/rsa/public.pem
      - RSA_PRIVATE_KEY=/etc/rsa/private.pem
      # - SSL_CERT=./certs/cert.pem
      # - SSL_KEY=./certs/key.pem
      - UPLOAD_DIR=/app/uploads/
    env_file:
      - ${ENV}.env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ${RSA_PUBLIC_KEY}:/etc/rsa/public.pem
      - ${RSA_PRIVATE_KEY}:/etc/rsa/private.pem
      - ${UPLOAD_DIR}:/app/uploads/
    networks:
      - default
      - pub_net
      - auth_net
    restart: unless-stopped
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql # Can this be baked into either image?
      - ./postgres-data/:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "5555:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   volumes:
  #     - ./pgadmin-data:/var/lib/pgadmin
  #   restart: unless-stopped
  redis:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD} # Can this be made optional?
    restart: unless-stopped

volumes:
  postgres-data:
  # pgadmin-data:

networks:
  pub_net:
    driver: bridge
    name: pub_net
  auth_net:
    driver: bridge
    name: auth_net
